# yaml-language-server: $schema=./pkg/config/config.schema.json

# See pkg/config/config.go for the full list of configuration options.
# This file is used to debugging purposes only.

version: "1"

log_level: info
dev_mode: true
access_logs:
  enabled: true
  output:
    file:
      enabled: true
      path: "access.log"
  fields:
    - key: "service"
      value_from:
        request_header: "x-service"
    - key: "operationName"
      value_from:
        context_field: operation_name
    - key: "operationSha256"
      value_from:
        context_field: operation_sha256
    - key: "responseErrorMessage"
      value_from:
        context_field: response_error_message
    - key: "serviceNames"
      value_from:
        context_field: operation_service_names
    - key: "operationHash"
      value_from:
        context_field: operation_hash
    - key: "errorCodes"
      value_from:
        context_field: graphql_error_codes
    - key: "operationType"
      value_from:
        context_field: operation_type
    - key: "persistentOperationSha256"
      value_from:
        context_field: persisted_operation_sha256
    - key: "serviceNames"
      value_from:
        context_field: graphql_error_service_names
    - key: "operationParsingTime"
      value_from:
        context_field: operation_parsing_time
    - key: "operationPlanningTime"
      value_from:
        context_field: operation_planning_time
    - key: "operationNormalizationTime"
      value_from:
        context_field: operation_normalization_time
    - key: "operationValidationTime"
      value_from:
        context_field: operation_validation_time
